version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27019:27017
    restart: always
    environment:
      MONGO_INITDB_DATABASE : product
    volumes:
      - ../database/product:/data/db
#  product:
#      image: sales-portal/productcatalogservice:1.0
#      ports:
#        - 8082:8082
#      environment:
#        spring.data.mongodb.host: mongo
#        spring.data.mongodb.port: 27017